Import('env')

env.SharedLibrary('dmf_control_board', Glob('*.cpp'), SHLIBPREFIX='')

if 'docs' in COMMAND_LINE_TARGETS:
    import SCons.Environment

    SCons.Environment.apply_tools(env, tools=['default', 'doxygen'], toolpath='.')
    doc = env.Doxygen('doxy.cfg')
    env.AlwaysBuild(doc)
